"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type RecordItem = Record<string, string | number | boolean | null | undefined>;
type Session = { access_token: string; tenant_id: string; user_id: string };
const API_URL = process.env.NEXT_PUBLIC_API_URL || "/api";
const sections = ["Overview", "Customers", "Operations", "Quotes & bookings", "Conversations", "Knowledge", "Approvals"] as const;
type Section = (typeof sections)[number];

function money(value: unknown) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(Number(value || 0) / 100); }
function date(value: unknown) { return value ? new Date(String(value)).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }) : "—"; }
function Label({ children }: { children: React.ReactNode }) { return <label className="field">{children}</label>; }
function Empty({ children }: { children: React.ReactNode }) { return <p className="empty">{children}</p>; }

export default function Home() {
  const [session, setSession] = useState<Session | null>(null);
  const [section, setSection] = useState<Section>("Overview");
  const [businesses, setBusinesses] = useState<RecordItem[]>([]);
  const [businessId, setBusinessId] = useState("");
  const [data, setData] = useState<Record<string, RecordItem[]>>({});
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  const [messageConversation, setMessageConversation] = useState("");
  const [messages, setMessages] = useState<RecordItem[]>([]);

  const request = useCallback(async (path: string, options: RequestInit = {}, token = session?.access_token) => {
    const response = await fetch(`${API_URL}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(typeof body.detail === "string" ? body.detail : "Request failed");
    return body;
  }, [session]);

  const loadBusinessData = useCallback(async (id: string, token = session?.access_token) => {
    if (!id || !token) return;
    const paths: Record<string, string> = { customers: `/v1/customers?business_id=${id}`, leads: `/v1/leads?business_id=${id}`, services: `/v1/services?business_id=${id}`, vehicles: `/v1/vehicles?business_id=${id}`, quotes: `/v1/quotes?business_id=${id}`, bookings: `/v1/bookings?business_id=${id}`, conversations: `/v1/conversations?business_id=${id}`, knowledge: `/v1/knowledge-sources?business_id=${id}`, approvals: "/v1/actions/pending" };
    const entries = await Promise.all(Object.entries(paths).map(async ([key, path]) => [key, await request(path, {}, token)] as const));
    setData(Object.fromEntries(entries));
  }, [request, session]);

  const refresh = useCallback(async (token = session?.access_token) => {
    if (!token) return;
    const nextBusinesses = await request("/v1/businesses", {}, token) as RecordItem[];
    setBusinesses(nextBusinesses);
    const saved = localStorage.getItem("mbas-business-id");
    const selected = nextBusinesses.some((item) => item.id === businessId) ? businessId : nextBusinesses.find((item) => item.id === saved)?.id?.toString() || nextBusinesses[0]?.id?.toString() || "";
    setBusinessId(selected);
    if (selected) await loadBusinessData(selected, token); else setData({});
  }, [businessId, loadBusinessData, request, session]);

  useEffect(() => {
    const saved = localStorage.getItem("mbas-session");
    if (!saved) return;
    try { const parsed = JSON.parse(saved) as Session; setSession(parsed); void refresh(parsed.access_token).catch(() => { localStorage.removeItem("mbas-session"); setSession(null); }); } catch { localStorage.removeItem("mbas-session"); }
  // Session restoration deliberately runs once.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => { if (businessId) localStorage.setItem("mbas-business-id", businessId); }, [businessId]);

  async function authenticate(event: FormEvent<HTMLFormElement>, mode: "signup" | "login") {
    event.preventDefault(); setBusy(true); setNotice(""); const fields = new FormData(event.currentTarget);
    try {
      const payload = mode === "signup" ? { organization_name: fields.get("organization"), name: fields.get("name"), email: fields.get("email"), password: fields.get("password") } : { email: fields.get("email"), password: fields.get("password") };
      const result = await request(`/v1/auth/${mode}`, { method: "POST", body: JSON.stringify(payload) }, undefined) as Session;
      localStorage.setItem("mbas-session", JSON.stringify(result)); setSession(result); setNotice("You are signed in. Create a business to start operating."); await refresh(result.access_token);
    } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to sign in"); } finally { setBusy(false); }
  }

  async function submit(event: FormEvent<HTMLFormElement>, path: string, buildPayload: (fields: FormData) => Record<string, unknown>) {
    event.preventDefault(); const form = event.currentTarget; setBusy(true); setNotice("");
    try { const result = await request(path, { method: "POST", body: JSON.stringify(buildPayload(new FormData(form))) }); setNotice(`Saved successfully: ${String((result as RecordItem).id || "updated")}`); form.reset(); await refresh(); }
    catch (error) { setNotice(error instanceof Error ? error.message : "Unable to save"); } finally { setBusy(false); }
  }
  async function decide(id: string, decision: "approved" | "rejected") { setBusy(true); try { await request(`/v1/actions/${id}/approval`, { method: "POST", body: JSON.stringify({ decision }) }); setNotice(`Action ${decision}.`); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to update action"); } finally { setBusy(false); } }
  async function verify(id: string) { setBusy(true); try { await request(`/v1/knowledge-sources/${id}/verify`, { method: "POST", body: "{}" }); setNotice("Knowledge source verified."); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to verify source"); } finally { setBusy(false); } }
  async function openConversation(id: string) { setMessageConversation(id); try { setMessages(await request(`/v1/conversations/${id}/messages`) as RecordItem[]); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to load messages"); } }
  async function sendConversationMessage(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const fields = new FormData(form); try { await request(`/v1/conversations/${messageConversation}/messages`, { method: "POST", body: JSON.stringify({ content: fields.get("content") }) }); form.reset(); await openConversation(messageConversation); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to send message"); } }

  const selectedBusiness = businesses.find((item) => item.id === businessId);
  const counts = useMemo(() => ({ customers: data.customers?.length || 0, leads: data.leads?.length || 0, bookings: data.bookings?.length || 0, conversations: data.conversations?.length || 0 }), [data]);
  if (!session) return <AuthScreen authenticate={authenticate} busy={busy} notice={notice} />;
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="mark">M</span><span><strong>MBAs</strong><small>Business OS</small></span></div><nav>{sections.map((item) => <button key={item} className={section === item ? "nav-item active" : "nav-item"} onClick={() => setSection(item)}>{item}</button>)}</nav><button className="nav-item signout" onClick={() => { localStorage.removeItem("mbas-session"); setSession(null); }}>Sign out</button></aside><section className="workspace"><header className="topbar"><div><p className="eyebrow">Tenant workspace</p><h1>{section}</h1></div><div className="business-picker"><label>Active business<select value={businessId} onChange={(event) => { setBusinessId(event.target.value); void loadBusinessData(event.target.value); }}><option value="">Select a business</option>{businesses.map((business) => <option key={String(business.id)} value={String(business.id)}>{String(business.name)}</option>)}</select></label></div></header>{notice && <div className="notice" role="status">{notice}</div>}{!businessId ? <BusinessSetup submit={submit} busy={busy} /> : <DashboardContent section={section} business={selectedBusiness} data={data} busy={busy} submit={submit} decide={decide} verify={verify} openConversation={openConversation} messageConversation={messageConversation} messages={messages} sendMessage={sendConversationMessage} counts={counts} />}</section></main>;
}

function AuthScreen({ authenticate, busy, notice }: { authenticate: (event: FormEvent<HTMLFormElement>, mode: "signup" | "login") => Promise<void>; busy: boolean; notice: string }) {
  const [mode, setMode] = useState<"signup" | "login">("signup");
  return <main className="auth-page"><section className="auth-intro"><div className="brand"><span className="mark">M</span><span><strong>MBAs</strong><small>MANI Business Automation System</small></span></div><p className="eyebrow">Operations workspace</p><h1>Run every customer journey from one trusted place.</h1><p>CRM, travel operations, conversations, knowledge and safe approvals for your team.</p></section><section className="auth-card"><div className="tabs"><button className={mode === "signup" ? "active" : ""} onClick={() => setMode("signup")}>Create workspace</button><button className={mode === "login" ? "active" : ""} onClick={() => setMode("login")}>Sign in</button></div><form onSubmit={(event) => void authenticate(event, mode)}>{mode === "signup" && <><Label>Organization<input name="organization" required minLength={2} placeholder="Mani Travels" /></Label><Label>Your name<input name="name" required minLength={2} placeholder="Owner name" /></Label></>}<Label>Email<input name="email" type="email" required placeholder="you@business.com" /></Label><Label>Password<input name="password" type="password" required minLength={12} placeholder="At least 12 characters" /></Label><button className="primary" disabled={busy}>{busy ? "Working…" : mode === "signup" ? "Create secure workspace" : "Sign in"}</button></form>{notice && <p className="form-notice">{notice}</p>}<p className="hint">Local account sign-in is ready. Google/OIDC can be enabled with provider credentials at deployment.</p></section></main>;
}

function BusinessSetup({ submit, busy }: { submit: (event: FormEvent<HTMLFormElement>, path: string, buildPayload: (fields: FormData) => Record<string, unknown>) => Promise<void>; busy: boolean }) { return <section className="setup-card"><p className="eyebrow">First step</p><h2>Create the business your team will operate</h2><p>A business separates customers, pricing, conversations and approvals inside your organization.</p><form onSubmit={(event) => void submit(event, "/v1/businesses", (fields) => ({ name: fields.get("name"), timezone: fields.get("timezone") || "Asia/Kolkata" }))}><Label>Business name<input name="name" required placeholder="Mani Car Travels" /></Label><Label>Timezone<input name="timezone" defaultValue="Asia/Kolkata" required /></Label><button className="primary" disabled={busy}>Create business</button></form></section>; }

function DashboardContent(props: { section: Section; business: RecordItem | undefined; data: Record<string, RecordItem[]>; busy: boolean; submit: (event: FormEvent<HTMLFormElement>, path: string, buildPayload: (fields: FormData) => Record<string, unknown>) => Promise<void>; decide: (id: string, decision: "approved" | "rejected") => Promise<void>; verify: (id: string) => Promise<void>; openConversation: (id: string) => Promise<void>; messageConversation: string; messages: RecordItem[]; sendMessage: (event: FormEvent<HTMLFormElement>) => Promise<void>; counts: Record<string, number> }) {
  const { section, data, submit, busy, decide, verify, openConversation, messageConversation, messages, sendMessage, counts } = props;
  const businessId = String(props.business?.id || ""); const items = (key: string) => data[key] || [];
  if (section === "Overview") return <><div className="metrics">{[["Customers", counts.customers], ["Open leads", counts.leads], ["Bookings", counts.bookings], ["Conversations", counts.conversations]].map(([label, value]) => <article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</div><section className="panel"><p className="eyebrow">Ready to operate</p><h2>{String(props.business?.name)}</h2><p>Build your travel catalog, receive leads, create deterministic quotes, schedule bookings and respond from the shared conversation timeline.</p><div className="checklist"><span>1. Add a service and vehicle</span><span>2. Register a customer or lead</span><span>3. Create a quote, then confirm a booking</span></div></section></>;
  if (section === "Customers") return <TwoColumn title="Customers & leads" form={<><form onSubmit={(event) => void submit(event, "/v1/customers", (f) => ({ business_id: businessId, display_name: f.get("name") || null, phone_e164: f.get("phone") || null, email: f.get("email") || null }))}><h3>Add customer</h3><Label>Name<input name="name" placeholder="Customer name" /></Label><Label>Phone<input name="phone" placeholder="+919876543210" /></Label><Label>Email<input name="email" type="email" placeholder="customer@email.com" /></Label><button className="primary" disabled={busy}>Save customer</button></form><form onSubmit={(event) => void submit(event, "/v1/leads", (f) => ({ business_id: businessId, customer_id: f.get("customer_id") || null, source: f.get("source") || "manual", notes: f.get("notes") || null }))}><h3>Capture lead</h3><Label>Linked customer<select name="customer_id"><option value="">No customer linked</option>{items("customers").map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.display_name || item.phone_e164 || item.id)}</option>)}</select></Label><Label>Source<input name="source" defaultValue="manual" /></Label><Label>Notes<textarea name="notes" placeholder="Trip requirements or follow-up notes" /></Label><button className="secondary" disabled={busy}>Create lead</button></form></>} lists={<><List title="Customers" rows={items("customers")} render={(r) => <><strong>{String(r.display_name || "Unnamed customer")}</strong><span>{String(r.phone_e164 || r.email || "No contact")}</span></>} /><List title="Leads" rows={items("leads")} render={(r) => <><strong>{String(r.source)} · {String(r.status)}</strong><span>{String(r.notes || "No notes")}</span></>} /></>} />;
  if (section === "Operations") return <TwoColumn title="Travel operations" form={<><form onSubmit={(event) => void submit(event, "/v1/services", (f) => ({ business_id: businessId, name: f.get("name"), unit_price_paise: Math.round(Number(f.get("price") || 0) * 100) }))}><h3>Price a service</h3><Label>Service name<input name="name" required placeholder="Hyderabad airport transfer" /></Label><Label>Price (₹)<input name="price" type="number" min="0" step="0.01" required /></Label><button className="primary" disabled={busy}>Save service</button></form><form onSubmit={(event) => void submit(event, "/v1/vehicles", (f) => ({ business_id: businessId, registration_number: f.get("registration"), vehicle_type: f.get("type"), seats: Number(f.get("seats")) }))}><h3>Add vehicle</h3><Label>Registration<input name="registration" required placeholder="TS09AB1234" /></Label><Label>Vehicle type<input name="type" required placeholder="Innova Crysta" /></Label><Label>Seats<input name="seats" type="number" min="1" max="100" required /></Label><button className="secondary" disabled={busy}>Save vehicle</button></form></>} lists={<><List title="Service catalog" rows={items("services")} render={(r) => <><strong>{String(r.name)}</strong><span>{money(r.unit_price_paise)} · {r.active ? "active" : "inactive"}</span></>} /><List title="Fleet" rows={items("vehicles")} render={(r) => <><strong>{String(r.registration_number)}</strong><span>{String(r.vehicle_type)} · {String(r.seats)} seats · {String(r.status)}</span></>} /></>} />;
  if (section === "Quotes & bookings") return <TwoColumn title="Quotes & bookings" form={<><form onSubmit={(event) => void submit(event, "/v1/quotes", (f) => ({ business_id: businessId, customer_id: f.get("customer_id") || null, lines: [{ service_id: f.get("service_id"), quantity: Number(f.get("quantity") || 1) }] }))}><h3>Create verified quote</h3><Label>Customer<select name="customer_id"><option value="">Walk-in customer</option>{items("customers").map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.display_name || item.id)}</option>)}</select></Label><Label>Service<select name="service_id" required><option value="">Select service</option>{items("services").map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.name)} — {money(item.unit_price_paise)}</option>)}</select></Label><Label>Quantity<input name="quantity" type="number" min="1" defaultValue="1" required /></Label><button className="primary" disabled={busy}>Calculate quote</button></form><form onSubmit={(event) => void submit(event, "/v1/bookings", (f) => ({ business_id: businessId, quote_id: f.get("quote_id"), customer_id: f.get("customer_id") || null, vehicle_id: f.get("vehicle_id") || null, pickup_at: new Date(String(f.get("pickup_at"))).toISOString(), pickup_location: f.get("pickup"), drop_location: f.get("drop") }))}><h3>Confirm booking</h3><Label>Quote<select name="quote_id" required><option value="">Select quote</option>{items("quotes").map((item) => <option key={String(item.id)} value={String(item.id)}>{money(item.total_paise)} · {String(item.status)}</option>)}</select></Label><Label>Vehicle<select name="vehicle_id"><option value="">Assign later</option>{items("vehicles").map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.registration_number)}</option>)}</select></Label><Label>Pickup time<input name="pickup_at" type="datetime-local" required /></Label><Label>Pickup<input name="pickup" required placeholder="Pickup location" /></Label><Label>Destination<input name="drop" required placeholder="Drop location" /></Label><button className="secondary" disabled={busy}>Create booking</button></form></>} lists={<><List title="Quotes" rows={items("quotes")} render={(r) => <><strong>{money(r.total_paise)} · {String(r.status)}</strong><span>Created {date(r.created_at)}</span></>} /><List title="Bookings" rows={items("bookings")} render={(r) => <><strong>{String(r.pickup_location)} → {String(r.drop_location)}</strong><span>{date(r.pickup_at)} · {money(r.total_paise)} · {String(r.status)}</span></>} /></>} />;
  if (section === "Conversations") return <TwoColumn title="Shared conversation inbox" form={<><form onSubmit={(event) => void submit(event, "/v1/conversations", (f) => ({ business_id: businessId, customer_id: f.get("customer_id") || null, channel: f.get("channel"), language: f.get("language") || null }))}><h3>Start conversation</h3><Label>Customer<select name="customer_id"><option value="">Unidentified contact</option>{items("customers").map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.display_name || item.id)}</option>)}</select></Label><Label>Channel<select name="channel"><option value="web">Web chat</option><option value="whatsapp">WhatsApp</option><option value="phone">Phone</option><option value="telegram">Telegram</option></select></Label><Label>Language<input name="language" placeholder="en-IN, te-IN, hi-IN" /></Label><button className="primary" disabled={busy}>Open conversation</button></form>{messageConversation && <form onSubmit={(event) => void sendMessage(event)}><h3>Reply in timeline</h3><div className="message-stream">{messages.map((message) => <p key={String(message.id)} className={String(message.sender_type)}><b>{String(message.sender_type)}</b>{String(message.content)}</p>)}</div><Label>Customer message<textarea name="content" required placeholder="Type a test customer message" /></Label><button className="secondary">Send & get agent reply</button></form>}</>} lists={<List title="Conversations" rows={items("conversations")} render={(r) => <button className="row-button" onClick={() => void openConversation(String(r.id))}><strong>{String(r.channel)} · {String(r.status)}</strong><span>{String(r.language || "Language not set")} · {date(r.started_at)}</span></button>} />} />;
  if (section === "Knowledge") return <TwoColumn title="Verified business knowledge" form={<form onSubmit={(event) => void submit(event, "/v1/knowledge-sources", (f) => ({ business_id: businessId, title: f.get("title"), source_type: f.get("source_type"), content: f.get("content") }))}><h3>Add a source</h3><Label>Title<input name="title" required placeholder="Airport transfer policy" /></Label><Label>Source type<select name="source_type"><option value="faq">FAQ</option><option value="document">Document</option><option value="website">Website</option><option value="spreadsheet">Spreadsheet</option></select></Label><Label>Verified facts<textarea name="content" required placeholder="Write facts your agents are allowed to use." /></Label><button className="primary" disabled={busy}>Add for review</button></form>} lists={<List title="Knowledge review queue" rows={items("knowledge")} render={(r) => <div className="list-row"><strong>{String(r.title)}</strong><span>{String(r.source_type)} · {String(r.verification_status)}</span>{r.verification_status === "pending" && <button className="small" onClick={() => void verify(String(r.id))}>Verify</button>}</div>} />} />;
  return <TwoColumn title="Approval inbox" form={<form onSubmit={(event) => void submit(event, "/v1/actions", (f) => ({ business_id: businessId, action_name: f.get("action_name"), payload: { note: f.get("note") }, idempotency_key: crypto.randomUUID() }))}><h3>Request guarded action</h3><Label>Action<select name="action_name"><option value="booking.modify">Modify booking (approval)</option><option value="booking.cancel">Cancel booking (approval)</option><option value="payment.refund">Payment refund (owner/admin)</option></select></Label><Label>Reason<textarea name="note" required placeholder="Explain why this action is needed" /></Label><button className="primary" disabled={busy}>Request approval</button></form>} lists={<List title="Pending decisions" rows={items("approvals")} render={(r) => <div className="list-row"><strong>{String(r.action_name)} <em className={`risk ${String(r.risk_level)}`}>{String(r.risk_level)}</em></strong><span>{String(r.requested_by)} · {date(r.created_at)}</span><div className="row-actions"><button className="small" onClick={() => void decide(String(r.id), "approved")}>Approve</button><button className="small danger" onClick={() => void decide(String(r.id), "rejected")}>Reject</button></div></div>} />} />;
}

function TwoColumn({ title, form, lists }: { title: string; form: React.ReactNode; lists: React.ReactNode }) { return <><h2 className="section-title">{title}</h2><div className="two-column"><section className="panel form-panel">{form}</section><section className="list-stack">{lists}</section></div></>; }
function List({ title, rows, render }: { title: string; rows: RecordItem[]; render: (row: RecordItem) => React.ReactNode }) { return <section className="panel list-panel"><h3>{title}</h3>{rows.length ? <div className="list">{rows.map((row) => <div className="list-row" key={String(row.id)}>{render(row)}</div>)}</div> : <Empty>No records yet.</Empty>}</section>; }
